# Generated by Django 5.0.3 on 2024-04-03 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('number_of_works', models.IntegerField()),
                ('still_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('fic', 'Fiction'), ('mys', 'Mystery'), ('nfc', 'Non-Fiction'), ('fan', 'Fantasy'), ('tcr', 'True Crime'), ('hor', 'Horror'), ('his', 'History'), ('mem', 'Memoir'), ('grn', 'Graphic Novel'), ('bio', 'Biography'), ('sci', 'Science'), ('dra', 'Drama'), ('hum', 'Humor'), ('adv', 'Adventure'), ('rom', 'Romance')], default='fic', max_length=3)),
                ('description', models.TextField(max_length=500)),
                ('word_count', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.author')),
            ],
        ),
    ]
