# Generated by Django 5.0.3 on 2024-04-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='still_active',
            field=models.BooleanField(verbose_name='Still Active'),
        ),
        migrations.AlterField(
            model_name='book',
            name='word_count',
            field=models.IntegerField(verbose_name='Word Count'),
        ),
    ]
