# Generated by Django 5.0.3 on 2024-04-04 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_book_publication_date_alter_author_still_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('established', models.DateField()),
                ('website', models.CharField(max_length=100)),
                ('headquarters', models.CharField(max_length=100)),
                ('image', models.CharField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(verbose_name='Publication Date'),
        ),
        migrations.AddField(
            model_name='book',
            name='published_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.publisher'),
            preserve_default=False,
        ),
    ]
